# Generated by Django 3.0.8 on 2020-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('contactno', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
